Repository NeKzor/SourceAutoRecord, pull requests merged in 2019-12, with the labels that each got.

#26 sar_tas_frame_next fix
  src/Features/Tas/CommandQueuer.cpp
Labels: bugfix

#32 Reduced loading times
  src/Cheats.cpp
  src/Cheats.hpp
  src/Features/Cvars.cpp
Labels: enhancement

#33 sar_record_at
  src/Modules/EngineDemoRecorder.cpp
  src/Modules/Server.cpp
  src/Modules/Server.hpp
Labels: feature

#34 Implemented sar_pause
  src/Modules/Server.cpp
  src/Modules/Server.hpp
Labels: feature
